### ISSUE TITLE
Image building problems - docker authentification - Mac OS - Docker desktop

### ISSUE THREAD

**Issue by smodlich** [openshift/source-to-image#1116]
Hi, 
I'm trying to run the following command. I get an empty error message:

` s2i build -E environment_rest . seldonio/seldon-core-s2i-python3:1.16.0-dev statsmodel-holts:0.1`

It's from [seldon tutorial](https://docs.seldon.io/projects/seldon-core/en/latest/examples/statsmodels.html).

Running with log level 5 I get:
```
I0329 10:12:42.012250   48100 build.go:52] Running S2I version "v1.3.5-dirty"
I0329 10:12:42.013061   48100 util.go:58] Getting docker credentials for seldonio/seldon-core-s2i-python3:1.16.0-dev
F0329 10:12:42.030042   48100 build.go:161] Error response from daemon: 
```

Looking at [build.go 161](https://github.com/openshift/source-to-image/blob/master/pkg/cmd/cli/cmd/build.go) I think the issue is related to S2I not getting the docker credentials. 

Content of ~/docker/config.json

```
{
        "auths": {
                "https://index.docker.io/v1/": {}
        },
        "credsStore": "desktop"
}
```

OS: MacOS 13.1
Docker Engine: v20.10.23
Docker Desktop: 4.17.0

What I already tried:
`docker login`
(before I got another error message, now I get empty error message)

I can pull the image in docker no problem.

**Comment by mwbisma09** [comment]
Hi @smodlich,

I'm currently on the same issue, did you manage to resolve or have a workaround?

`%s2i build https://github.com/openshift/ruby-hello-world centos/ruby-22-centos7 hello-world-app`

`FATAL: Error response from daemon:`

Arch: arm64
OS:  Ventura 13.3.1
Docker Engine: 20.10.24
Docker Desktop: 4.18.0

**Comment by ryannix123** [comment]
I believe that's fixed in the latest version of `s2i`

**Comment by smodlich** [comment]
Can confirm it works now. I updated s2i to newest version 1.3.6.

**Comment by mwbisma09** [comment]
@ryannix123 & @smodlich 

perhaps I'm facing a different one.
I was on 1.3.6 and tried downloaded & replace the current one, yet the issue still persist.

```
mwbisma@A8022-Wafi-MBA20 docker % s2i version
s2i v1.3.6
mwbisma@A8022-Wafi-MBA20 docker % s2i build https://github.com/openshift/ruby-hello-world centos/ruby-22-centos7 hello-world-app
FATAL: Error response from daemon: 
```

**Comment by muhammad-asn** [comment]
Is it any update? Still got issue

**Comment by coreydaley** [comment]
If you are experiencing problems, please open a new issue, as we do not monitor closed issues.
