### ISSUE TITLE
filesystem build adds an extra directory

### ISSUE THREAD

**Issue by accursoft** [openshift/source-to-image#363]
`s2i build {git repository}` adds the files from the repository to `/tmp/src`. `s2i build some/path` adds the files to `tmp/src/path`.

This makes it tricky to write an `assemble` script which works for sources from both git repos and the local file system.

**Comment by GrahamDumpleton** [comment]
Is this related to #348. That is, fixed by it, or caused by it.

**Comment by mfojtik** [comment]
@accursoft can you please confirm that this issue was fixed?

**Comment by accursoft** [comment]
It's not fixed, and I'm not clear which changeset was supposed to have fixed it.
